# Generated by Django 2.0.7 on 2018-08-06 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadFiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfCsv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csvFile', models.ImageField(blank=True, upload_to='media/imageStore')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('csvDoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadFiles.Document')),
            ],
        ),
    ]
