# Generated by Django 2.0.7 on 2018-08-06 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadFiles', '0002_pdfcsv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfcsv',
            name='csvFile',
            field=models.FileField(blank=True, upload_to='media/pdfStore'),
        ),
    ]
